### PR TITLE
add wiremock as an test-dep and implement test for

### PR DESCRIPTION
**Pull request by jbellmann**
lets start writing some tests for #52

### CODE REVIEW

**Comment by LappleApple** [comment]
@jbellmann @harti2006 @duergner Hey, this PR hasn't been addressed since August 2016. What would you guys like to do here?

**Comment by duergner** [comment]
If I understand the related issue correctly we release a version on Central. Not sure whether that one got testing to solve the issue.

From what I can see has changed that should be a fairly small PR actually. But we must definitely address the merge conflicts first.

@jbellmann definitely has a better understanding here what should be done.

**Comment by jbellmann** [comment]
True, this PR was created to present and discuss  a possible workaround for #52. I also [released a  version](http://search.maven.org/#artifactdetails%7Corg.zalando.stups%7Ctokens%7C0.9.9-gh52-1%7Cjar) for that to maven-central to make it possible to test it in other [projects (eg.planB)](https://github.com/zalando/planb-provider/issues/129). That issue was closed 4 days ago without proper feedback. I'm guessing they never had a look into the problem because @hjacobs was [writing about experiencing the issue in PlanB](https://github.com/zalando/tokens/issues/52#issuecomment-235640559).

What now? I don' t know.
Seems that the issue #52 is not be present to any other teams. Or can be fixed with an version upgrade of [http-client >= 4.5.2](http://search.maven.org/#artifactdetails%7Corg.apache.httpcomponents%7Chttpclient%7C4.5.3%7Cjar).
Furthermore, fetching tokens via http is not used anymore in the future-setup (Kubernetes / secrets).

So we could close the PR and #52 as 'wont-fix' but keep them if it becomes an issue again.

**Comment by LappleApple** [comment]
@jbellmann Hi Joerg: Are you also considering how this PR might help/affect non-Zalandos? Given that it's on public GitHub the assumption is that development would take non-Zalandos' potential use cases in mind. If that's not the case, and external users/contributors are not part of your target audience now, then I'd consider moving this to the Incubator so that non-Zalandos don't get confused.

**Comment by duergner** [comment]
If upgrading to http-client >= 4.5.2 does actually fix the underlying issue I'd vote to label the issue as won't fix.

**Pull request closed without merging**
