### PR TITLE
Decrease log level to info

### LINKED ISSUE #137: Removing warning when tokenInfoUri is not configured
When using [riptide](https://github.com/zalando/riptide), we get a logging warning from org.zalando.stups.tokens.TokenVerifyRunner with "No AccessToken-Verification enabled because no 'tokenInfoUri' was configured"

## Detailed Description
It would be nice to either change riptide to provide `tokenInfoUri` or to reduce the log level of this information. A third option could also be get rid of this feature.
I created an issue in [riptide repo](https://github.com/zalando/riptide/issues/549) to add this field, and it was proposed that `tokens` would change instead.

## Context

We try to have only warnings and errors in our logs when it is something that we should act on it, so we would like to remove this warning.

### PR DESCRIPTION
**Pull request by jbellmann**
fixes #137

### CODE REVIEW

**Comment by ssalome** [comment]
👍

**Comment by ssalome** [comment]
@jbellmann ping :)

**Comment by isitinschi** [comment]
is anyone going to merge this PR?

**Comment by jbellmann** [comment]
👍

**Comment by ChristianLohmann** [comment]
:+1:

**Pull request merged**
