### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kzimnicki-zalando**
I've added example for multiple token injection. I had to read source code to figured out which separator is expected.

### CODE REVIEW

**Comment by harti2006** [comment]
:+1:

**Comment by harti2006** [comment]
Thanks for the PR!

**Comment by LappleApple** [comment]
@harti2006 @kzimnicki-zalando The code here suggests a dependency on Zign. Am I right?

**Comment by jbellmann** [comment]
👍

**Comment by harti2006** [comment]
:+1:

**Comment by jbellmann** [comment]
@LappleApple For local testing (on developers machine with 'static tokens') one way to fetch access-tokens could be using zign, that's correct. But in normal use (production on EC2-Instances), 'tokens' will fetch access-tokens by requesting authorization-server with credentials found in 'client.json' and 'user.json'.

I wouldn't call it a dependency. It's only one way to provide access-tokens on developers machine. Its also possible on developers machine to provide 'client.json' and 'user.json' with valid content and point to the tokens-lib to that directory.

**Comment by LappleApple** [comment]
Thanks, @jbellmann. This was good info, so I added it (reworked) to the "Local Testing" section; you should probably check to make sure I edited it accurately.

**Pull request merged**
